### ISSUE TITLE
`EFCore 6` support (Method not found exception) 

### ISSUE THREAD

**Issue by luizhlelis** [rafaelpadovezi/Ziggurat#10]
In `EFCore 6`, the `ModelExtensions` class suffered many updates, and the `FindEntityType` method [was turned obsolete](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.modelextensions.findentitytype?view=efcore-6.0). You're using it [here](https://github.com/rafaelpadovezi/Ziggurat/blob/5939a5894b576a28eb5803c38b45130e904c0869/src/Ziggurat/Idempotency/IdempotencyMiddleware.cs#L66). The following error is thrown when using `Ziggurat` with `EFCore 6`:

```bash
Method not found: 'Microsoft.EntityFrameworkCore.Metadata.IEntityType Microsoft.EntityFrameworkCore.ModelExtensions.FindEntityType(Microsoft.EntityFrameworkCore.Metadata.IModel, System.Type)'.
 ---> System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.IEntityType Microsoft.EntityFrameworkCore.ModelExtensions.FindEntityType(Microsoft.EntityFrameworkCore.Metadata.IModel, System.Type)'.
   at DotNetCore.CAP.Internal.SubscribeInvoker.InvokeAsync(ConsumerContext context, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.SubscribeDispatcher.InvokeConsumerMethodAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.Internal.SubscribeInvoker.InvokeAsync(ConsumerContext context, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.SubscribeDispatcher.InvokeConsumerMethodAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
```

Take a look at other packages that faced similar issues:

[EFCore.BulkExtensions](https://github.com/borisdj/EFCore.BulkExtensions/issues/485)
[AutoMapper.Collection.EFCore](https://github.com/AutoMapper/AutoMapper.Collection.EFCore/issues/55)

**Comment by rafaelpadovezi** [comment]
Thanks for bringing this issue to my attention @luizhlelis. Added support for `net6` fo Ziggurat, which enables usings CAP 6.0.* and EF Core 6.0.*
The changes were shipped on the `1.0.0` version (without the beta suffix)
